def on_overlap_tile(sprite, location):
    if controller.A.is_pressed():
        tiles.set_tile_at(location, sprites.dungeon.green_switch_down)
        tiles.set_wall_at(tiles.get_tile_location(14, 13), False)
        tiles.set_tile_at(tiles.get_tile_location(15, 13),
            sprites.dungeon.door_open_east)
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.green_switch_up,
    on_overlap_tile)

def on_overlap_tile2(sprite2, location2):
    pass
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.door_open_east,
    on_overlap_tile2)

def on_overlap_tile3(sprite3, location3):
    tiles.set_current_tilemap(tilemap("""
        level2
        """))
    info.change_countdown_by(20)
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.stair_west,
    on_overlap_tile3)

mySprite = sprites.create(img("""
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        .......22...22......
        ......2222.2222.....
        ......222222222.....
        ......222222222.....
        .......2222222......
        ........22222.......
        .........222........
        ..........2.........
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        """),
    SpriteKind.player)
controller.move_sprite(mySprite)
tiles.set_tilemap(tilemap("""
    level_1
    """))
tiles.place_on_random_tile(mySprite, sprites.dungeon.stair_ladder)
scene.camera_follow_sprite(mySprite)
info.start_countdown(20)